#!/usr/bin/env python3
"""
Isaac Sim Grasp Execution Node

This ROS2 node runs on the remote machine (192.168.100.12) and executes
grasp commands generated by Contact-GraspNet.

It subscribes to grasp execution topics, transforms camera-frame poses to
robot base coordinates, and executes the pregrasp -> grasp -> retreat
motion sequence using MoveIt IK service.

Architecture:
1. Subscribe to /piper/grasp_execution (JSON) or individual pose topics
2. Get current end effector pose from /piper/end_pose
3. Transform camera-frame grasp poses to base_link/world frame
4. Call MoveIt IK service (/compute_ik) to get joint angles
5. Publish joint commands to /piper/joint_ctrl for execution

Coordinate Transform Chain:
- Grasp pose in camera frame -> transform to gripper_base frame -> transform to world frame
- Camera relative to gripper_base: translation=[-0.045, 0.0, 0.065], euler=[0, -90, 0]
- Robot base/end-effector world transforms are read from live ROS topics / TF

Usage:
    python3 grasp_execution_node.py

Requirements (on remote machine):
    - ROS2 (Humble/Jazzy)
    - MoveIt2 with IK service running
    - Isaac Sim with Piper robot simulation
"""

import json
import threading
import time
import numpy as np
from scipy.spatial.transform import Rotation as R

# ROS2 imports
try:
    import rclpy
    from rclpy.node import Node
    from rclpy.qos import QoSProfile, ReliabilityPolicy, HistoryPolicy
    from rclpy.action import ActionClient
    from std_msgs.msg import Bool, Float32, String
    from geometry_msgs.msg import Pose, PoseArray, PoseStamped
    from sensor_msgs.msg import JointState
    from moveit_msgs.msg import MoveItErrorCodes, RobotTrajectory
    from moveit_msgs.srv import ComputeIK
    from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint
    ROS2_AVAILABLE = True
except ImportError:
    ROS2_AVAILABLE = False
    print("Warning: ROS2 not available. This script must run on a machine with ROS2 installed.")


def euler_to_rotation_matrix(euler_deg: list) -> np.ndarray:
    """Convert Euler angles (degrees) to rotation matrix (XYZ order)."""
    rot = R.from_euler('xyz', euler_deg, degrees=True)
    return rot.as_matrix()


def pose_to_matrix(pose_msg: Pose) -> np.ndarray:
    """Convert ROS Pose message to 4x4 transformation matrix."""
    matrix = np.eye(4)
    matrix[0, 3] = pose_msg.position.x
    matrix[1, 3] = pose_msg.position.y
    matrix[2, 3] = pose_msg.position.z

    quat = [pose_msg.orientation.x, pose_msg.orientation.y,
            pose_msg.orientation.z, pose_msg.orientation.w]
    rot = R.from_quat(quat)
    matrix[:3, :3] = rot.as_matrix()

    return matrix


def matrix_to_pose(matrix: np.ndarray) -> Pose:
    """Convert 4x4 transformation matrix to ROS Pose message."""
    pose = Pose()
    pose.position.x = float(matrix[0, 3])
    pose.position.y = float(matrix[1, 3])
    pose.position.z = float(matrix[2, 3])

    rot = R.from_matrix(matrix[:3, :3])
    quat = rot.as_quat()
    pose.orientation.x = float(quat[0])
    pose.orientation.y = float(quat[1])
    pose.orientation.z = float(quat[2])
    pose.orientation.w = float(quat[3])

    return pose


def matrix_to_pose_stamped(matrix: np.ndarray, frame_id: str, timestamp=None) -> PoseStamped:
    """Convert 4x4 matrix to PoseStamped."""
    pose_stamped = PoseStamped()
    pose_stamped.header.frame_id = frame_id
    if timestamp:
        pose_stamped.header.stamp = timestamp
    pose_stamped.pose = matrix_to_pose(matrix)
    return pose_stamped


class CoordinateTransformer:
    """
    Handles coordinate transformations between camera, gripper, and world frames.

    Transform chain:
    camera_frame -> gripper_base_frame -> world_frame

    Camera is mounted on the gripper with:
    - translation: [-0.045, 0.0, 0.065] (4.5cm forward, 6.5cm above gripper_base)
    - rotation: euler [0, -90, 0] (pitch -90°, pointing forward)
    """

    def __init__(self):
        # TF parent->child transforms.
        self.gripper_to_camera_translation = np.array([-0.045, 0.0, 0.065], dtype=np.float32)
        self.gripper_to_camera_euler = [0, -90, 0]  # degrees, XYZ order

        self._gripper_to_camera = np.eye(4, dtype=np.float32)
        self._gripper_to_camera[:3, :3] = euler_to_rotation_matrix(self.gripper_to_camera_euler)
        self._gripper_to_camera[:3, 3] = self.gripper_to_camera_translation
        self._camera_to_gripper = np.linalg.inv(self._gripper_to_camera)

        # Camera link -> optical frame (ROS camera convention).
        self._camera_to_optical = np.eye(4, dtype=np.float32)
        self._camera_to_optical[:3, :3] = R.from_quat([-0.5, 0.5, -0.5, 0.5]).as_matrix()
        self._optical_to_camera = np.linalg.inv(self._camera_to_optical)

        # Robot base/world transforms should come from live ROS topics/TF.
        self.robot_base_position = np.zeros(3, dtype=np.float32)
        self.robot_base_rotation = np.eye(3, dtype=np.float32)
        self.reference_frame = 'world'
        self.planning_frame = 'base_link'

        # Base pose in world, and its inverse for world -> base conversion.
        self._base_to_world = np.eye(4, dtype=np.float32)
        self._base_to_world[:3, :3] = self.robot_base_rotation
        self._base_to_world[:3, 3] = self.robot_base_position
        self._world_to_base = np.linalg.inv(self._base_to_world)

        print("CoordinateTransformer initialized:")
        print(f"  Gripper->Camera: translation={self.gripper_to_camera_translation}, euler={self.gripper_to_camera_euler}")
        print(f"  Robot base in world: {self.robot_base_position}")

    def transform_optical_to_camera(self, pose_optical: np.ndarray) -> np.ndarray:
        """Transform pose from camera optical frame to camera link frame."""
        return self._optical_to_camera @ pose_optical

    def transform_camera_to_gripper(self, pose_camera: np.ndarray) -> np.ndarray:
        """Transform pose from camera link frame to gripper_base frame."""
        return self._camera_to_gripper @ pose_camera

    def transform_gripper_to_camera(self, pose_gripper: np.ndarray) -> np.ndarray:
        """Transform pose from gripper_base frame to camera frame."""
        return self._gripper_to_camera @ pose_gripper

    def transform_pose_to_base(self,
                               pose_input: np.ndarray,
                               end_pose_world: np.ndarray,
                               input_frame: str = 'camera_optical_frame',
                               end_pose_frame: str = 'map') -> np.ndarray:
        """
        Transform pose from a supported input frame to robot base frame.

        Supported input frames:
        - camera_optical_frame / end_cam_optical_frame
        - camera / end_cam
        - world
        - base_link

        Args:
            pose_input: 4x4 matrix in input frame
            end_pose_world: 4x4 matrix of current end effector in world frame
            input_frame: name of the input frame

        Returns:
            4x4 matrix in robot base frame
        """
        frame = input_frame or 'camera_optical_frame'

        if frame in ('base_link', 'base'):
            return pose_input

        if frame == 'world':
            return self._world_to_base @ pose_input

        if frame in ('camera_optical_frame', 'end_cam_optical_frame', 'optical'):
            pose_camera = self.transform_optical_to_camera(pose_input)
        elif frame in ('camera', 'end_cam', 'camera_link'):
            pose_camera = pose_input
        else:
            raise ValueError(f'Unsupported input frame: {frame}')

        pose_gripper = self.transform_camera_to_gripper(pose_camera)
        pose_reference = end_pose_world @ pose_gripper
        if end_pose_frame in (self.planning_frame, 'base'):
            return pose_reference

        if end_pose_frame != self.reference_frame:
            raise ValueError(
                f'Unsupported end pose frame: {end_pose_frame!r}; expected {self.reference_frame!r} or {self.planning_frame!r}'
            )

        pose_base = self._world_to_base @ pose_reference

        return pose_base

    def convert_pose_between_reference_and_base(self,
                                                pose_matrix: np.ndarray,
                                                source_frame: str) -> np.ndarray:
        """Convert a pose expressed in reference/base frame into base frame."""
        if source_frame in (self.planning_frame, 'base'):
            return pose_matrix
        if source_frame == self.reference_frame:
            return self._world_to_base @ pose_matrix
        raise ValueError(
            f'Unsupported source frame: {source_frame!r}; expected {self.reference_frame!r} or {self.planning_frame!r}'
        )


class GraspExecutionNode(Node):
    """
    ROS2 node that executes grasp commands from Contact-GraspNet.

    Motion sequence:
    1. Move to pregrasp position (offset from grasp along approach axis)
    2. Move to grasp position
    3. Close gripper
    4. Move to retreat position (lift up along approach axis)
    5. Optionally move to drop position
    """

    def __init__(self):
        super().__init__('grasp_execution_node')

        # Coordinate transformer
        self.transformer = CoordinateTransformer()

        # Current end effector pose in world frame
        self._end_pose_world = np.eye(4)
        self._end_pose_lock = threading.Lock()
        self._end_pose_valid = False
        self._end_pose_frame = self.transformer.reference_frame
        self._auto_align_orientation = True

        # Execution state
        self._executing = False
        self._execution_lock = threading.Lock()

        # Gripper state
        self._gripper_open = True
        self._gripper_width = 0.08  # default opening

        # QoS profile
        qos = QoSProfile(
            reliability=ReliabilityPolicy.RELIABLE,
            history=HistoryPolicy.KEEP_LAST,
            depth=10
        )

        qos_best_effort = QoSProfile(
            reliability=ReliabilityPolicy.BEST_EFFORT,
            history=HistoryPolicy.KEEP_LAST,
            depth=1
        )

        # Subscribe to end effector pose (for coordinate transform)
        self.end_pose_sub = self.create_subscription(
            PoseStamped,
            '/piper/end_pose',
            self._end_pose_callback,
            qos_best_effort
        )

        # Subscribe to grasp execution command (JSON format)
        self.grasp_exec_sub = self.create_subscription(
            String,
            '/piper/grasp_execution',
            self._grasp_execution_callback,
            qos
        )

        # Subscribe to individual pose topics (alternative)
        self.pregrasp_sub = self.create_subscription(
            PoseStamped,
            '/piper/pregrasp_pose',
            self._pregrasp_callback,
            qos
        )

        self.target_grasp_sub = self.create_subscription(
            PoseStamped,
            '/piper/target_grasp',
            self._target_grasp_callback,
            qos
        )

        self.retreat_sub = self.create_subscription(
            PoseStamped,
            '/piper/postgrasp_pose',
            self._retreat_callback,
            qos
        )

        self.gripper_opening_sub = self.create_subscription(
            Float32,
            '/piper/gripper_opening',
            self._gripper_opening_callback,
            qos
        )

        self.execute_trigger_sub = self.create_subscription(
            Bool,
            '/piper/execute_grasp',
            self._execute_trigger_callback,
            qos
        )

        # Publishers for joint control
        self.joint_ctrl_pub = self.create_publisher(
            JointTrajectory,
            '/piper/joint_ctrl',
            qos
        )

        self.gripper_ctrl_pub = self.create_publisher(
            Float32,
            '/piper/gripper_command',
            qos
        )

        # MoveIt IK service client
        self.ik_client = self.create_client(
            ComputeIK,
            '/compute_ik'
        )

        # Current target poses (in camera frame, stored for execution)
        self._pregrasp_pose_camera = None
        self._target_grasp_pose_camera = None
        self._retreat_pose_camera = None

        print("GraspExecutionNode initialized")
        print("  Subscribed to: /piper/grasp_execution, /piper/end_pose, etc.")
        print("  Publishers: /piper/joint_ctrl, /piper/gripper_command")
        print("  IK service: /compute_ik")

    def _log_pose_debug(self, label: str, pose_matrix: np.ndarray):
        """Log pose position, quaternion, and local axes for transform debugging."""
        rot = R.from_matrix(pose_matrix[:3, :3])
        quat = rot.as_quat()
        self.get_logger().info(
            f"{label}: pos={np.round(pose_matrix[:3, 3], 3).tolist()}, "
            f"quat={np.round(quat, 3).tolist()}"
        )
        self.get_logger().info(
            f"{label}: axes x={np.round(pose_matrix[:3, 0], 3).tolist()}, "
            f"y={np.round(pose_matrix[:3, 1], 3).tolist()}, "
            f"z={np.round(pose_matrix[:3, 2], 3).tolist()}"
        )

    def _align_pose_orientation(self,
                                origin_pose: np.ndarray,
                                target_pose: np.ndarray) -> np.ndarray:
        """Rebuild target orientation so the tool Z axis points toward the target position."""
        aligned_pose = target_pose.copy()
        delta = target_pose[:3, 3] - origin_pose[:3, 3]
        distance = np.linalg.norm(delta)
        if distance < 1e-6:
            return aligned_pose

        z_axis = delta / distance

        x_seed = origin_pose[:3, 0]
        x_axis = x_seed - np.dot(x_seed, z_axis) * z_axis
        if np.linalg.norm(x_axis) < 1e-6:
            up_seed = np.array([0.0, 0.0, 1.0], dtype=np.float32)
            x_axis = np.cross(up_seed, z_axis)
        if np.linalg.norm(x_axis) < 1e-6:
            alt_seed = np.array([1.0, 0.0, 0.0], dtype=np.float32)
            x_axis = np.cross(alt_seed, z_axis)

        x_axis = x_axis / np.linalg.norm(x_axis)
        y_axis = np.cross(z_axis, x_axis)
        y_axis = y_axis / np.linalg.norm(y_axis)
        x_axis = np.cross(y_axis, z_axis)
        x_axis = x_axis / np.linalg.norm(x_axis)

        aligned_pose[:3, 0] = x_axis
        aligned_pose[:3, 1] = y_axis
        aligned_pose[:3, 2] = z_axis
        return aligned_pose

    def _end_pose_callback(self, msg: PoseStamped):
        """Update current end effector pose."""
        with self._end_pose_lock:
            self._end_pose_world = pose_to_matrix(msg.pose)
            self._end_pose_frame = msg.header.frame_id or self.transformer.reference_frame
            self._end_pose_valid = True

    def _grasp_execution_callback(self, msg: String):
        """
        Process full grasp execution JSON command.

        This is the preferred method - receives all poses and parameters in one message.
        """
        try:
            data = json.loads(msg.data)
            self.get_logger().info(f"Received grasp execution command: frame_id={data.get('frame_id')}")

            input_frame = data.get('frame', 'camera_optical_frame')

            # Extract poses from JSON.
            pose_camera = np.array(data['pose'])
            pregrasp_camera = np.array(data['pregrasp_pose'])
            retreat_camera = np.array(data['retreat_pose'])

            gripper_opening = data.get('gripper_opening', 0.08)
            score = data.get('score', 0.0)

            self.get_logger().info(f"  Score: {score:.3f}, Gripper opening: {gripper_opening:.3f}")
            self.get_logger().info(f"  Input frame: {input_frame}")

            # Execute the grasp sequence
            self._execute_grasp_sequence(
                pregrasp_camera,
                pose_camera,
                retreat_camera,
                gripper_opening,
                input_frame=input_frame,
            )

        except json.JSONDecodeError as e:
            self.get_logger().error(f"JSON decode error: {e}")
        except KeyError as e:
            self.get_logger().error(f"Missing key in execution data: {e}")
        except Exception as e:
            self.get_logger().error(f"Execution error: {e}")

    def _pregrasp_callback(self, msg: PoseStamped):
        """Store pregrasp pose (in camera frame)."""
        self._pregrasp_pose_camera = pose_to_matrix(msg.pose)
        self.get_logger().info("Stored pregrasp pose")

    def _target_grasp_callback(self, msg: PoseStamped):
        """Store target grasp pose (in camera frame)."""
        self._target_grasp_pose_camera = pose_to_matrix(msg.pose)
        self.get_logger().info("Stored target grasp pose")

    def _retreat_callback(self, msg: PoseStamped):
        """Store retreat pose (in camera frame)."""
        self._retreat_pose_camera = pose_to_matrix(msg.pose)
        self.get_logger().info("Stored retreat pose")

    def _gripper_opening_callback(self, msg: Float32):
        """Store gripper opening width."""
        self._gripper_width = msg.data
        self.get_logger().info(f"Stored gripper opening: {self._gripper_width:.3f}")

    def _execute_trigger_callback(self, msg: Bool):
        """
        Trigger grasp execution when all poses are stored.

        This is the alternative method - poses come separately via individual topics.
        """
        if msg.data:
            if (
                self._pregrasp_pose_camera is not None
                and self._target_grasp_pose_camera is not None
                and self._retreat_pose_camera is not None
            ):
                self._execute_grasp_sequence(
                    self._pregrasp_pose_camera,
                    self._target_grasp_pose_camera,
                    self._retreat_pose_camera,
                    self._gripper_width
                )
                # Clear stored poses after execution
                self._pregrasp_pose_camera = None
                self._target_grasp_pose_camera = None
                self._retreat_pose_camera = None
            else:
                self.get_logger().warn("Execute trigger received but poses not complete")

    def _execute_grasp_sequence(self,
                                pregrasp_camera: np.ndarray,
                                grasp_camera: np.ndarray,
                                retreat_camera: np.ndarray,
                                gripper_opening: float,
                                input_frame: str = 'camera_optical_frame'):
        """
        Execute the full grasp motion sequence.

        Sequence:
        1. Open gripper
        2. Move to pregrasp position
        3. Move to grasp position
        4. Close gripper
        5. Move to retreat position
        """
        with self._execution_lock:
            if self._executing:
                self.get_logger().warn("Already executing, skipping")
                return
            self._executing = True

        try:
            # Wait for valid end pose
            if not self._wait_for_end_pose(timeout=2.0):
                self.get_logger().error("No valid end pose received")
                return

            # Get current end pose
            with self._end_pose_lock:
                end_pose_world = self._end_pose_world.copy()
                end_pose_frame = self._end_pose_frame
            self._log_pose_debug("Current end pose", end_pose_world)
            self.get_logger().info(f"Current end pose frame: {end_pose_frame}")
            current_base = self.transformer.convert_pose_between_reference_and_base(end_pose_world, end_pose_frame)
            self._log_pose_debug("Current end pose base", current_base)

            # Transform poses to base frame
            pregrasp_base = self.transformer.transform_pose_to_base(
                pregrasp_camera, end_pose_world, input_frame, end_pose_frame=end_pose_frame
            )
            grasp_base = self.transformer.transform_pose_to_base(
                grasp_camera, end_pose_world, input_frame, end_pose_frame=end_pose_frame
            )
            retreat_base = self.transformer.transform_pose_to_base(
                retreat_camera, end_pose_world, input_frame, end_pose_frame=end_pose_frame
            )

            self.get_logger().info("Coordinate transform completed")
            self.get_logger().info(f"  Grasp position (base): {grasp_base[:3, 3]}")
            self._log_pose_debug("Target grasp base", grasp_base)

            delta_base = grasp_base[:3, 3] - current_base[:3, 3]
            delta_in_ee = current_base[:3, :3].T @ delta_base
            self.get_logger().info(f"  Delta current->target (world/base): {np.round(delta_base, 3).tolist()}")
            self.get_logger().info(f"  Delta current->target (ee local): {np.round(delta_in_ee, 3).tolist()}")

            if self._auto_align_orientation:
                pregrasp_base = self._align_pose_orientation(current_base, pregrasp_base)
                grasp_base = self._align_pose_orientation(pregrasp_base, grasp_base)
                retreat_base = self._align_pose_orientation(grasp_base, retreat_base)
                self._log_pose_debug("Aligned pregrasp base", pregrasp_base)
                self._log_pose_debug("Aligned grasp base", grasp_base)
                self._log_pose_debug("Aligned retreat base", retreat_base)

            # Step 1: Open gripper
            self._open_gripper()

            # Step 2: Move to pregrasp
            self.get_logger().info("Moving to pregrasp position...")
            if not self._move_to_pose(pregrasp_base):
                self.get_logger().error("Failed to move to pregrasp")
                return

            # Step 3: Move to grasp
            self.get_logger().info("Moving to grasp position...")
            if not self._move_to_pose(grasp_base):
                self.get_logger().error("Failed to move to grasp")
                return

            # Step 4: Close gripper
            self._close_gripper(gripper_opening)

            # Step 5: Move to retreat
            self.get_logger().info("Moving to retreat position...")
            if not self._move_to_pose(retreat_base):
                self.get_logger().error("Failed to move to retreat")
                return

            self.get_logger().info("Grasp execution completed successfully!")

        except Exception as e:
            self.get_logger().error(f"Execution sequence error: {e}")

        finally:
            with self._execution_lock:
                self._executing = False

    def _wait_for_end_pose(self, timeout: float) -> bool:
        """Wait for valid end effector pose."""
        start_time = time.time()
        while time.time() - start_time < timeout:
            with self._end_pose_lock:
                if self._end_pose_valid:
                    return True
            time.sleep(0.1)
        return False

    def _open_gripper(self):
        """Open gripper to maximum width."""
        # Publish gripper open command
        msg = Float32()
        msg.data = 0.08  # maximum opening
        self.gripper_ctrl_pub.publish(msg)
        self._gripper_open = True
        self.get_logger().info("Gripper opened")
        time.sleep(0.5)  # wait for gripper to open

    def _close_gripper(self, width: float):
        """Close gripper to specified width."""
        # Publish gripper close command
        msg = Float32()
        msg.data = max(0.0, min(width, 0.08))  # clamp to valid range
        self.gripper_ctrl_pub.publish(msg)
        self._gripper_open = False
        self.get_logger().info(f"Gripper closed to {msg.data:.3f}")
        time.sleep(0.5)  # wait for gripper to close

    def _move_to_pose(self, target_pose_base: np.ndarray) -> bool:
        """
        Move robot to target pose using MoveIt IK.

        Args:
            target_pose_base: 4x4 matrix in robot base frame

        Returns:
            True if motion succeeded, False otherwise
        """
        # Convert to PoseStamped for IK request
        target_pose_msg = matrix_to_pose_stamped(target_pose_base, "base_link")

        # Call IK service
        if not self.ik_client.wait_for_service(timeout_sec=2.0):
            self.get_logger().error("IK service not available")
            return False

        # Build IK request
        request = ComputeIK.Request()
        request.ik_request.group_name = "piper_arm"  # adjust to your MoveIt group name
        request.ik_request.pose_stamped = target_pose_msg
        request.ik_request.timeout = rclpy.duration.Duration(seconds=1.0)

        # Call service synchronously
        future = self.ik_client.call_async(request)
        rclpy.spin_until_future_complete(self, future, timeout_sec=3.0)

        if not future.done():
            self.get_logger().error("IK service call timed out")
            return False

        try:
            response = future.result()
            if response.error_code.val != MoveItErrorCodes.SUCCESS:
                self.get_logger().error(f"IK failed with error code: {response.error_code.val}")
                return False

            # Extract joint positions from solution
            solution = response.solution
            joint_positions = solution.joint_state.position

            # Publish trajectory
            self._publish_joint_trajectory(joint_positions)
            return True

        except Exception as e:
            self.get_logger().error(f"IK response error: {e}")
            return False

    def _publish_joint_trajectory(self, joint_positions: list):
        """Publish joint trajectory for execution."""
        trajectory = JointTrajectory()
        trajectory.header.stamp = self.get_clock().now().to_msg()
        trajectory.joint_names = [
            "joint1", "joint2", "joint3", "joint4", "joint5", "joint6"
        ]  # adjust to your robot's joint names

        point = JointTrajectoryPoint()
        point.positions = joint_positions
        point.velocities = [0.0] * len(joint_positions)
        point.time_from_start = rclpy.duration.Duration(seconds=2.0).to_msg()

        trajectory.points.append(point)

        self.joint_ctrl_pub.publish(trajectory)
        self.get_logger().info(f"Published joint trajectory: {joint_positions}")

        # Wait for motion to complete
        time.sleep(2.5)


def main():
    if not ROS2_AVAILABLE:
        print("ERROR: ROS2 is not available. Please run this script on a machine with ROS2 installed.")
        return

    rclpy.init()

    node = GraspExecutionNode()

    print("GraspExecutionNode running. Press Ctrl+C to stop.")

    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
