#!/usr/bin/env python3
"""
Grasp Execution Node for Piper Robot

This ROS2 node executes grasp commands generated by Contact-GraspNet.
It subscribes to grasp execution topics and uses MoveIt2 to plan and execute
the pregrasp -> grasp -> retreat motion sequence.

Usage (system Python, not conda):
    source /opt/ros/humble/setup.bash
    source /home/jjl/git_projects/piper_ros/install/setup.bash
    export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    python3 grasp_executor.py

Requirements:
    - MoveIt2 running (piper_moveit_bridge.py)
    - ROS2 Humble
    - moveit_py package
"""

import json
import time
import threading
import numpy as np
from scipy.spatial.transform import Rotation as R

import rclpy
from rclpy.node import Node
from rclpy.action import ActionClient
from rclpy.callback_groups import ReentrantCallbackGroup
from std_msgs.msg import String, Bool
from geometry_msgs.msg import PoseStamped, Pose
from control_msgs.action import FollowJointTrajectory
from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint
from moveit_msgs.srv import GetPositionIK
from moveit_msgs.msg import MoveItErrorCodes, RobotTrajectory
from sensor_msgs.msg import JointState


class GraspExecutor(Node):
    """
    Executes grasp commands using MoveIt2 IK service and trajectory actions.
    """

    def __init__(self):
        super().__init__('grasp_executor')

        # Callback group for concurrent execution
        self._callback_group = ReentrantCallbackGroup()

        # Execution lock to prevent concurrent grasp executions
        self._execution_lock = threading.Lock()
        self._executing = False

        # Current joint states
        self._current_joints = {}
        self._joint_names = ['joint1', 'joint2', 'joint3', 'joint4', 'joint5', 'joint6']

        # Subscribe to joint states for current position
        self.joint_state_sub = self.create_subscription(
            JointState,
            '/joint_states',
            self._joint_state_callback,
            10
        )

        # Subscribe to grasp execution command (JSON format)
        self.grasp_exec_sub = self.create_subscription(
            String,
            '/piper/grasp_execution',
            self._grasp_execution_callback,
            10,
            callback_group=self._callback_group
        )

        # Subscribe to execute trigger
        self.execute_trigger_sub = self.create_subscription(
            Bool,
            '/piper/execute_grasp',
            self._execute_trigger_callback,
            10,
            callback_group=self._callback_group
        )

        # Subscribe to target grasp pose (alternative)
        self.target_grasp_sub = self.create_subscription(
            PoseStamped,
            '/piper/target_grasp',
            self._target_grasp_callback,
            10
        )

        # IK service client
        self.ik_client = self.create_client(
            GetPositionIK,
            '/compute_ik',
            callback_group=self._callback_group
        )

        # Arm trajectory action client
        self.arm_action_client = ActionClient(
            self,
            FollowJointTrajectory,
            'arm_controller/follow_joint_trajectory',
            callback_group=self._callback_group
        )

        # Gripper trajectory action client
        self.gripper_action_client = ActionClient(
            self,
            FollowJointTrajectory,
            'gripper_controller/follow_joint_trajectory',
            callback_group=self._callback_group
        )

        # Stored grasp poses (from individual topics)
        self._pregrasp_pose = None
        self._grasp_pose = None
        self._retreat_pose = None
        self._gripper_opening = 0.08

        # Default gripper opening (fully open)
        self._gripper_open = 0.08
        self._gripper_closed = 0.0

        self.get_logger().info('GraspExecutor initialized')
        self.get_logger().info('  Subscribed: /piper/grasp_execution')
        self.get_logger().info('  IK service: /compute_ik')
        self.get_logger().info('  Actions: arm_controller, gripper_controller')

    def _joint_state_callback(self, msg: JointState):
        """Store current joint states."""
        for i, name in enumerate(msg.name):
            if name in self._joint_names or name == 'joint7':
                self._current_joints[name] = msg.position[i] if i < len(msg.position) else 0.0

    def _grasp_execution_callback(self, msg: String):
        """
        Process grasp execution JSON command.

        JSON format:
        {
            'pose': [[4x4 matrix]],
            'pregrasp_pose': [[4x4 matrix]],
            'retreat_pose': [[4x4 matrix]],
            'gripper_opening': float,
            'score': float
        }
        """
        try:
            data = json.loads(msg.data)
            self.get_logger().info(f'Received grasp command: frame_id={data.get("frame_id")}, score={data.get("score", 0):.3f}')

            # Extract poses (4x4 matrices as lists)
            grasp_matrix = np.array(data.get('pose', []))
            pregrasp_matrix = np.array(data.get('pregrasp_pose', []))
            retreat_matrix = np.array(data.get('retreat_pose', []))
            gripper_opening = data.get('gripper_opening', 0.08)

            if grasp_matrix.shape != (4, 4):
                self.get_logger().error(f'Invalid grasp pose shape: {grasp_matrix.shape}')
                return

            # Execute grasp sequence
            self._execute_grasp_sequence(pregrasp_matrix, grasp_matrix, retreat_matrix, gripper_opening)

        except json.JSONDecodeError as e:
            self.get_logger().error(f'JSON decode error: {e}')
        except Exception as e:
            self.get_logger().error(f'Execution error: {e}')

    def _target_grasp_callback(self, msg: PoseStamped):
        """Store target grasp pose."""
        self._grasp_pose = self._pose_stamped_to_matrix(msg)
        self.get_logger().info('Stored target grasp pose')

    def _execute_trigger_callback(self, msg: Bool):
        """Trigger execution when poses are stored."""
        if msg.data and self._grasp_pose is not None:
            # Simple execution without pregrasp/retreat
            self._execute_single_pose(self._grasp_pose)

    def _pose_stamped_to_matrix(self, msg: PoseStamped) -> np.ndarray:
        """Convert PoseStamped to 4x4 matrix."""
        matrix = np.eye(4)
        matrix[0, 3] = msg.pose.position.x
        matrix[1, 3] = msg.pose.position.y
        matrix[2, 3] = msg.pose.position.z

        quat = [msg.pose.orientation.x, msg.pose.orientation.y,
                msg.pose.orientation.z, msg.pose.orientation.w]
        rot = R.from_quat(quat)
        matrix[:3, :3] = rot.as_matrix()
        return matrix

    def _matrix_to_pose(self, matrix: np.ndarray) -> Pose:
        """Convert 4x4 matrix to ROS Pose."""
        pose = Pose()
        pose.position.x = float(matrix[0, 3])
        pose.position.y = float(matrix[1, 3])
        pose.position.z = float(matrix[2, 3])

        rot = R.from_matrix(matrix[:3, :3])
        quat = rot.as_quat()
        pose.orientation.x = float(quat[0])
        pose.orientation.y = float(quat[1])
        pose.orientation.z = float(quat[2])
        pose.orientation.w = float(quat[3])
        return pose

    def _execute_grasp_sequence(self, pregrasp, grasp, retreat, gripper_opening):
        """
        Execute the full grasp motion sequence:
        1. Open gripper
        2. Move to pregrasp position
        3. Move to grasp position
        4. Close gripper
        5. Move to retreat position
        """
        with self._execution_lock:
            if self._executing:
                self.get_logger().warn('Already executing, skipping')
                return
            self._executing = True

        try:
            # Step 1: Open gripper
            self.get_logger().info('Step 1: Opening gripper...')
            self._execute_gripper(self._gripper_open)
            time.sleep(0.5)

            # Step 2: Move to pregrasp
            if pregrasp.shape == (4, 4):
                self.get_logger().info('Step 2: Moving to pregrasp...')
                self._execute_pose(pregrasp)
                time.sleep(1.0)

            # Step 3: Move to grasp
            self.get_logger().info('Step 3: Moving to grasp...')
            self._execute_pose(grasp)
            time.sleep(1.0)

            # Step 4: Close gripper
            self.get_logger().info(f'Step 4: Closing gripper to {gripper_opening:.3f}...')
            self._execute_gripper(gripper_opening)
            time.sleep(0.5)

            # Step 5: Move to retreat
            if retreat.shape == (4, 4):
                self.get_logger().info('Step 5: Moving to retreat...')
                self._execute_pose(retreat)
                time.sleep(1.0)

            self.get_logger().info('Grasp execution completed!')

        except Exception as e:
            self.get_logger().error(f'Execution sequence error: {e}')

        finally:
            with self._execution_lock:
                self._executing = False

    def _execute_single_pose(self, pose_matrix):
        """Execute a single pose (move to position)."""
        with self._execution_lock:
            if self._executing:
                return
            self._executing = True

        try:
            self._execute_pose(pose_matrix)
        finally:
            with self._execution_lock:
                self._executing = False

    def _execute_pose(self, pose_matrix: np.ndarray):
        """
        Execute motion to a target pose using IK service.
        """
        # Wait for IK service
        if not self.ik_client.wait_for_service(timeout_sec=2.0):
            self.get_logger().error('IK service not available')
            return False

        # Create IK request
        request = GetPositionIK.Request()
        request.ik_request.group_name = 'piper_arm'
        request.ik_request.pose_stamped.header.frame_id = 'base_link'
        request.ik_request.pose_stamped.pose = self._matrix_to_pose(pose_matrix)
        request.ik_request.timeout.sec = 2

        # Call IK service
        future = self.ik_client.call_async(request)

        # Wait for result (with timeout)
        start_time = time.time()
        while not future.done() and time.time() - start_time < 5.0:
            rclpy.spin_once(self, timeout_sec=0.1)

        if not future.done():
            self.get_logger().error('IK service call timed out')
            return False

        try:
            response = future.result()
            if response.error_code.val != MoveItErrorCodes.SUCCESS:
                self.get_logger().error(f'IK failed: error code {response.error_code.val}')
                return False

            # Extract joint positions
            solution = response.solution.joint_state
            joint_positions = dict(zip(solution.name, solution.position))

            self.get_logger().info(f'IK solution: {joint_positions}')

            # Execute trajectory
            self._execute_arm_trajectory(joint_positions)
            return True

        except Exception as e:
            self.get_logger().error(f'IK response error: {e}')
            return False

    def _execute_arm_trajectory(self, joint_positions: dict):
        """
        Send arm trajectory to MoveIt bridge.
        """
        # Wait for action server
        if not self.arm_action_client.wait_for_server(timeout_sec=2.0):
            self.get_logger().error('Arm action server not available')
            return

        # Create trajectory
        trajectory = JointTrajectory()
        trajectory.joint_names = self._joint_names

        # Create trajectory point
        point = JointTrajectoryPoint()
        point.positions = [joint_positions.get(name, 0.0) for name in self._joint_names]
        point.velocities = [0.0] * 6
        point.time_from_start.sec = 2
        point.time_from_start.nanosec = 0

        trajectory.points.append(point)

        # Create goal
        goal = FollowJointTrajectory.Goal()
        goal.trajectory = trajectory

        # Send goal
        self.get_logger().info(f'Sending arm trajectory: {point.positions}')
        future = self.arm_action_client.send_goal_async(goal)

        # Wait for acceptance
        start_time = time.time()
        while not future.done() and time.time() - start_time < 5.0:
            rclpy.spin_once(self, timeout_sec=0.1)

        if future.done():
            goal_handle = future.result()
            if goal_handle.accepted:
                self.get_logger().info('Arm trajectory accepted')
                # Wait for execution
                result_future = goal_handle.get_result_async()
                start_time = time.time()
                while not result_future.done() and time.time() - start_time < 10.0:
                    rclpy.spin_once(self, timeout_sec=0.1)
                if result_future.done():
                    self.get_logger().info('Arm trajectory executed')
            else:
                self.get_logger().error('Arm trajectory rejected')

    def _execute_gripper(self, width: float):
        """
        Send gripper command to MoveIt bridge.
        """
        # Wait for action server
        if not self.gripper_action_client.wait_for_server(timeout_sec=2.0):
            self.get_logger().error('Gripper action server not available')
            return

        # Clamp width to valid range
        width = max(0.0, min(width, 0.08))

        # Create trajectory
        trajectory = JointTrajectory()
        trajectory.joint_names = ['joint7']

        # Create trajectory point
        point = JointTrajectoryPoint()
        point.positions = [width]
        point.velocities = [0.0]
        point.time_from_start.sec = 1
        point.time_from_start.nanosec = 0

        trajectory.points.append(point)

        # Create goal
        goal = FollowJointTrajectory.Goal()
        goal.trajectory = trajectory

        # Send goal
        self.get_logger().info(f'Sending gripper command: width={width:.3f}')
        future = self.gripper_action_client.send_goal_async(goal)

        # Wait for acceptance
        start_time = time.time()
        while not future.done() and time.time() - start_time < 3.0:
            rclpy.spin_once(self, timeout_sec=0.1)

        if future.done():
            goal_handle = future.result()
            if goal_handle.accepted:
                self.get_logger().info('Gripper command accepted')
                # Wait for execution
                result_future = goal_handle.get_result_async()
                start_time = time.time()
                while not result_future.done() and time.time() - start_time < 3.0:
                    rclpy.spin_once(self, timeout_sec=0.1)
                if result_future.done():
                    self.get_logger().info('Gripper command executed')
            else:
                self.get_logger().error('Gripper command rejected')


def main():
    rclpy.init()

    executor = rclpy.executors.MultiThreadedExecutor()
    node = GraspExecutor()

    executor.add_node(node)

    print('GraspExecutor running. Press Ctrl+C to stop.')

    try:
        executor.spin()
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()